# Practical 3
## Finding Relationships Among Variables:
1. Use a dataset with multiple variables and perform correlation analysis to determine the strength and direction of relationships between pairs of variables.
2. Apply regression analysis to identify the relationship between an independent variable (e.g., advertising expenditure) and a dependent variable (e.g., sales revenue).

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
data = pd.read_csv(r"C:\Users\hp\Desktop\Lr_Tiwar_college\Datasets\diamonds.csv", encoding= 'unicode_escape')
df = data.copy()
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object 
 2   color    53940 non-null  object 
 3   clarity  53940 non-null  object 
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64  
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB


In [5]:
df.describe()

carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [6]:
print(df['cut'].unique())
print(df['color'].unique())
print(df['clarity'].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']


In [7]:
df['cut'] = df['cut'].replace({'Ideal': 0, 'Premium': 1, 'Good': 2, 'Very Good': 3, 'Fair': 4})
df['color'] = df['color'].replace({'E': 0, 'I': 1, 'J': 2, 'H': 3, 'F': 4, 'G': 5, 'D': 6})
# Define the mapping
clarity_mapping = {'SI2': 0, 'SI1': 1, 'VS1': 2, 'VS2': 3, 'VVS2': 4, 'VVS1': 5, 'I1': 6, 'IF': 7}

# Apply the mapping
df['clarity'] = df['clarity'].replace(clarity_mapping)


C:\Users\hp\AppData\Local\Temp\ipykernel_5136\2524847953.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['cut'] = df['cut'].replace({'Ideal': 0, 'Premium': 1, 'Good': 2, 'Very Good': 3, 'Fair': 4})
C:\Users\hp\AppData\Local\Temp\ipykernel_5136\2524847953.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['color'] = df['color'].replace({'E': 0, 'I': 1, 'J': 2, 'H': 3, 'F': 4, 'G': 5, 'D': 6})
C:\Users\hp\AppData\Local\Temp\ipykernel_5136\2524847953.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and 

In [8]:
df['cut'].unique(), df['color'].unique(), df['clarity'].unique()

(array([0, 1, 2, 3, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64))

In [9]:
correlation = df.corr()
correlation

carat       cut     color   clarity     depth     table     price  \
carat    1.000000  0.114426 -0.065386 -0.281218  0.028224  0.181618  0.921591   
cut      0.114426  1.000000 -0.029128 -0.118670  0.169916  0.381988  0.049421   
color   -0.065386 -0.029128  1.000000  0.032589 -0.001665 -0.033998 -0.016560   
clarity -0.281218 -0.118670  0.032589  1.000000 -0.025877 -0.133692 -0.140270   
depth    0.028224  0.169916 -0.001665 -0.025877  1.000000 -0.295779 -0.010647   
table    0.181618  0.381988 -0.033998 -0.133692 -0.295779  1.000000  0.127134   
price    0.921591  0.049421 -0.016560 -0.140270 -0.010647  0.127134  1.000000   
x        0.975094  0.105361 -0.055268 -0.305918 -0.025289  0.195344  0.884435   
y        0.951722  0.105319 -0.054762 -0.297037 -0.029341  0.183760  0.865421   
z        0.953387  0.126726 -0.055684 -0.299969  0.094924  0.150929  0.861249   

                x         y         z  
carat    0.975094  0.951722  0.953387  
cut      0.105361  0.105319  0.126726  
color   -0.055268 -0.054762 -0.055684  
clarity -0.305918 -0.297037 -0.299969  
depth   -0.025289 -0.029341  0.094924  
table    0.195344  0.183760  0.150929  
price    0.884435  0.865421  0.861249  
x        1.000000  0.974701  0.970772  
y        0.974701  1.000000  0.952006  
z        0.970772  0.952006  1.000000

In [10]:
# this wont work because clarity values lies from (0 to 7) which doesnt make sense to do correlation

In [11]:
from sklearn.model_selection import train_test_split

#split data
X = df[['carat']]
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [12]:
from sklearn.linear_model import LinearRegression

#create and train the  linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error(MAE): {mae}")
print(f"Mean Squared Error(MSE): {mse}")
print(f"R-squared: {r2}")


Mean Absolute Error(MAE): 1008.2926770010502
Mean Squared Error(MSE): 2379576.9001855766
R-squared: 0.8485280982587889


# Logisitic Regression 
## Multivariate Analysis

